name: CI/CD Masterclass
run-name: ${{ github.actor }} is running the pipeline
on: [push]
jobs: 
    Test-Workflow:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Starting Pipeline"
            - name: Check out repository code
              uses: actions/checkout@v6
            - name: Install Node
              uses: actions/setup-node@v4
            - name: Install dependencies
              run: npm install
            - name: Builds Slidedeck
              run: npm build