name: CI/CD Masterclass
run-name: ${{ github.actor }} is running the pipeline
on: 
  push:
    branches:
            - main
  workflow_dispatch:
    inputs:
        logLevel:
            description: "Logging Error"
            type: choice
            options: [error, warning]
            required: true

jobs: 
    markdown-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: DavidAnson/markdownlint-cli2-action@v24
              with:
                globs: slides.md
                # config: markdownlint-config.json

    build:
        needs: markdown-lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'npm'
            - run: npm ci
            - run: npm run build -- --base /${{ github.event.repository.name}}/ 
            - uses: actions/upload-pages-artifact@v5
              with: 
                path: dist/

    deploy:
        needs: build

        permissions:
            pages: write 
            id-token: write
            contents: read   

        environment:
            name: github-pages
            url: ${{ steps.deploy.outputs.page_url }}    

        runs-on: ubuntu-latest
        steps:          
            - name: Deploy
              id: deploy
              uses: actions/deploy-pages@v4